### PR TITLE
PropTypes update

### PR DESCRIPTION
**Pull request by basudz**
Updated PropTypes to import from new prop-types lib.

### CODE REVIEW

**Comment by syaau** [comment]
You will have to include the prop-types dependency as well, otherwise the library will fail to work with projects that do not use prop-types.

**Comment by basudz365** [comment]
Oops, committed to fast!  Updated the peer dependency.

**Review by syaau — CHANGES_REQUESTED** [review]
I think we need to add prop-types as a dependency rather than a peer-dependency, so that the library works well with the earlier version of react-native as well.

**Comment by basudz365** [comment]
Hmm, is this what you're looking for?

**Review by syaau — APPROVED** [review]

**Comment by basudz365** [comment]
Don't forget to update the version number and update npm ;)
Thanks!

**Pull request merged**
